/**
 * App Factory: MVP generator.
 * Given a deployment spec and optional template version, produces a minimal scaffold
 * in a temp directory for push to GitHub. No secrets; env placeholders only.
 * When APP_FACTORY_TEMPLATE_PATH (or DB source_path, e.g. infra/templates/nextjs/platforms) exists, copies that
 * Next.js multi-tenant template and applies spec substitutions.
 */

import { cpSync, mkdtempSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";
import { tmpdir } from "os";
import type { DeploymentSpec } from "./deployment-spec";
import { getAppFactoryTemplatePath } from "./env";

export type GeneratorInput = {
  spec: DeploymentSpec;
  /** Optional: template_registry.template_key (e.g. "platforms", "agent-stack"). */
  templateKey?: string | null;
  /** Optional: resolved absolute path to template directory. When set, this path is used instead of resolving from templateKey. */
  templatePath?: string | null;
  /** Optional: git ref for template (e.g. branch/tag). If not set, stub or local template is used. */
  templateGitRef?: string | null;
  /** Optional: env placeholder keys from template manifest (e.g. ["NEXT_PUBLIC_APP_URL"]). */
  envPlaceholders?: string[];
};

export type GeneratorResult =
  | { success: true; outputDir: string; usedTemplate: "platforms" | "stub" | "compose" }
  | { success: false; error: string };

/**
 * Copy template directory into outputDir, excluding .git and node_modules.
 */
function copyTemplateDir(templatePath: string, outputDir: string): void {
  cpSync(templatePath, outputDir, {
    recursive: true,
    filter: (src) => !src.includes(".git") && !src.includes("node_modules"),
  });
}

/**
 * Generate app scaffold into a temp directory.
 * If APP_FACTORY_TEMPLATE_PATH or resolved template path (e.g. infra/templates/nextjs/platforms) exists, copies that template and substitutes
 * app name, slug, and env placeholders. Otherwise uses a minimal stub with valid npm scripts.
 */
export function generateApp(input: GeneratorInput): GeneratorResult {
  const { spec, templateKey, templatePath: resolvedTemplatePath, envPlaceholders = [] } = input;
  const { app_metadata, branding } = spec;
  const name = app_metadata.name;
  const slug = app_metadata.slug;

  let outputDir: string;
  try {
    outputDir = mkdtempSync(join(tmpdir(), `app-factory-${slug}-`));
  } catch (e) {
    return { success: false, error: e instanceof Error ? e.message : "Failed to create temp dir." };
  }

  const templatePath =
    resolvedTemplatePath ?? (templateKey === "platforms" || !templateKey ? getAppFactoryTemplatePath() : null);

  if (templatePath) {
    try {
      copyTemplateDir(templatePath, outputDir);
      const pkgPath = join(outputDir, "package.json");
      const hasPackageJson = (() => {
        try {
          readFileSync(pkgPath, "utf-8");
          return true;
        } catch {
          return false;
        }
      })();
      const isCompose =
        templateKey === "agent-stack" ||
        (() => {
          try {
            readFileSync(join(outputDir, "docker-compose.yml"), "utf-8");
            return true;
          } catch {
            return false;
          }
        })();

      if (isCompose && !hasPackageJson) {
        const readme = `# ${name}\n\nGenerated by MOOD MNKY App Factory (Docker Compose stack).\n\nSlug: ${slug}\n`;
        writeFileSync(join(outputDir, "README.md"), readme, "utf-8");
        const envExamplePath = join(outputDir, ".env.example");
        try {
          readFileSync(envExamplePath, "utf-8");
        } catch {
          writeFileSync(
            envExamplePath,
            "# Generated by App Factory — fill in values before deploy.\n\n",
            "utf-8"
          );
        }
        return { success: true, outputDir, usedTemplate: "compose" };
      }

      if (hasPackageJson) {
        const pkg = JSON.parse(readFileSync(pkgPath, "utf-8")) as Record<string, unknown>;
        pkg.name = slug;
        pkg.description = name ?? slug;
        writeFileSync(pkgPath, JSON.stringify(pkg, null, 2), "utf-8");
        const readme = `# ${name}\n\nGenerated by MOOD MNKY App Factory from platforms template.\n\nSlug: ${slug}\n`;
        writeFileSync(join(outputDir, "README.md"), readme, "utf-8");
        const envExample = [
          "# Generated by App Factory — fill in values before deploy.",
          "NEXT_PUBLIC_ROOT_DOMAIN=",
          "KV_REST_API_URL=",
          "KV_REST_API_TOKEN=",
        ].join("\n");
        writeFileSync(join(outputDir, ".env.example"), envExample, "utf-8");
        return { success: true, outputDir, usedTemplate: "platforms" };
      }

      const readme = `# ${name}\n\nGenerated by MOOD MNKY App Factory.\n\nSlug: ${slug}\n`;
      writeFileSync(join(outputDir, "README.md"), readme, "utf-8");
      return { success: true, outputDir, usedTemplate: "compose" };
    } catch (e) {
      return { success: false, error: e instanceof Error ? e.message : "Failed to copy template." };
    }
  }

  try {
    const readme = `# ${name}\n\nGenerated by MOOD MNKY App Factory.\n\nSlug: ${slug}\n`;
    writeFileSync(join(outputDir, "README.md"), readme, "utf-8");

    const packageJson = {
      name: slug,
      version: "0.1.0",
      private: true,
      description: name,
      scripts: {
        build: "echo Build complete",
        start: "node -e \"require('http').createServer((q,r)=>{r.writeHead(200);r.end('OK');}).listen(3000)\"",
      },
    };
    writeFileSync(
      join(outputDir, "package.json"),
      JSON.stringify(packageJson, null, 2),
      "utf-8"
    );

    if (envPlaceholders.length > 0) {
      const envLines = ["# Generated by App Factory — fill in values before deploy.", ""];
      for (const key of envPlaceholders) {
        envLines.push(`${key}=`);
      }
      writeFileSync(join(outputDir, ".env.example"), envLines.join("\n"), "utf-8");
    } else {
      const defaultPlaceholders = [
        "NEXT_PUBLIC_APP_URL=",
        "NEXT_PUBLIC_SUPABASE_MT_URL=",
        "NEXT_PUBLIC_SUPABASE_MT_ANON_KEY=",
      ];
      writeFileSync(
        join(outputDir, ".env.example"),
        "# Generated by App Factory — fill in values before deploy.\n\n" +
          defaultPlaceholders.join("\n") +
          "\n",
        "utf-8"
      );
    }

    if (branding?.display_name) {
      writeFileSync(
        join(outputDir, "app-config.json"),
        JSON.stringify({ displayName: branding.display_name }, null, 2),
        "utf-8"
      );
    }

    return { success: true, outputDir, usedTemplate: "stub" };
  } catch (e) {
    return { success: false, error: e instanceof Error ? e.message : "Failed to write scaffold files." };
  }
}
