/**
 * App Factory: create GitHub repo and push generated files.
 * Uses Octokit REST (create repo, createOrUpdateFileContents for each file).
 */

import { readFileSync, readdirSync, statSync } from "fs";
import { join } from "path";
import { Octokit } from "octokit";
import { getGitHubToken } from "./env";

export type CreateRepoResult =
  | { success: true; repoUrl: string; defaultBranch: string; commitSha?: string; tag?: string }
  | { success: false; error: string };

const DEFAULT_BRANCH = "main";

export type PushToExistingRepoResult =
  | { success: true; commitSha?: string; tag?: string }
  | { success: false; error: string };

/**
 * Push generated files to an existing GitHub repo (overwrite). Used for "Pull changes" to sync template updates.
 */
export async function pushToExistingRepo(
  outputDir: string,
  repoUrl: string,
  branch: string = DEFAULT_BRANCH
): Promise<PushToExistingRepoResult> {
  const token = getGitHubToken();
  if (!token) return { success: false, error: "GITHUB_TOKEN or GITHUB_ACCESS_TOKEN not set." };

  const parsed = parseRepoUrl(repoUrl);
  if (!parsed) return { success: false, error: `Invalid GitHub repo URL: ${repoUrl}` };

  const octokit = new Octokit({ auth: token });
  const pushResult = await pushFilesToRepo(octokit, parsed.owner, parsed.repo, outputDir, branch);
  if (!pushResult.success) return pushResult;

  let commitSha: string | undefined;
  let tag: string | undefined;
  try {
    const { data: commits } = await octokit.rest.repos.listCommits({
      owner: parsed.owner,
      repo: parsed.repo,
      sha: branch,
      per_page: 1,
    });
    const latest = commits[0];
    if (latest?.sha) {
      commitSha = latest.sha;
      const tagName = `deploy-${new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19)}`;
      await octokit.rest.git.createRef({
        owner: parsed.owner,
        repo: parsed.repo,
        ref: `refs/tags/${tagName}`,
        sha: commitSha,
      });
      tag = tagName;
    }
  } catch {
    // non-fatal
  }
  return { success: true, commitSha, tag };
}

/**
 * List files in dir recursively (relative paths). Skips .git and node_modules.
 */
function listFiles(dir: string, base = ""): string[] {
  const entries = readdirSync(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const e of entries) {
    if (e.name === ".git" || e.name === "node_modules") continue;
    const rel = base ? `${base}/${e.name}` : e.name;
    if (e.isDirectory()) {
      files.push(...listFiles(join(dir, e.name), rel));
    } else {
      files.push(rel);
    }
  }
  return files;
}

/**
 * Push files from outputDir to an existing GitHub repo (overwrite). Used when repo already exists on retry.
 */
async function pushFilesToRepo(
  octokit: Octokit,
  owner: string,
  repoName: string,
  outputDir: string,
  branch: string
): Promise<{ success: true } | { success: false; error: string }> {
  const files = listFiles(outputDir);
  for (const relPath of files) {
    const fullPath = join(outputDir, relPath);
    let content: string;
    try {
      content = readFileSync(fullPath, "utf-8");
    } catch {
      continue;
    }
    const contentBase64 = Buffer.from(content, "utf-8").toString("base64");

    let sha: string | undefined;
    try {
      const { data } = await octokit.rest.repos.getContent({ owner, repo: repoName, path: relPath, ref: branch });
      if (!Array.isArray(data) && "sha" in data) sha = data.sha;
    } catch {
      // File does not exist; create without sha
    }

    try {
      await octokit.rest.repos.createOrUpdateFileContents({
        owner,
        repo: repoName,
        path: relPath,
        message: `Add ${relPath}`,
        content: contentBase64,
        branch,
        ...(sha ? { sha } : {}),
      });
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { success: false, error: `Failed to push file ${relPath}: ${msg}` };
    }
  }
  return { success: true };
}

/**
 * Create a new GitHub repo (or use existing) and push all files from outputDir.
 * If repo already exists, pushes to it (overwrite) so retries succeed.
 */
export async function createRepoAndPush(
  outputDir: string,
  repoName: string,
  options?: { description?: string }
): Promise<CreateRepoResult> {
  const token = getGitHubToken();
  if (!token) return { success: false, error: "GITHUB_TOKEN or GITHUB_ACCESS_TOKEN not set." };

  const octokit = new Octokit({ auth: token });
  const branch = DEFAULT_BRANCH;

  try {
    const { data: user } = await octokit.rest.users.getAuthenticated();
    const owner = user.login;

    try {
      await octokit.rest.repos.createForAuthenticatedUser({
        name: repoName,
        description: options?.description ?? `Generated by MOOD MNKY App Factory`,
        private: false,
        auto_init: true,
      });
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      if (!msg.includes("name already exists") && !msg.includes("Repository creation failed") && !msg.includes("name already exists on this account")) {
        throw err;
      }
      // Repo already exists: push to it (overwrite) so retries succeed
    }

    const pushResult = await pushFilesToRepo(octokit, owner, repoName, outputDir, branch);
    if (!pushResult.success) return { success: false, error: pushResult.error };

    let commitSha: string | undefined;
    let tag: string | undefined;
    try {
      const { data: commits } = await octokit.rest.repos.listCommits({
        owner,
        repo: repoName,
        sha: branch,
        per_page: 1,
      });
      const latest = commits[0];
      if (latest?.sha) {
        commitSha = latest.sha;
        const tagName = `deploy-${new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19)}`;
        await octokit.rest.git.createRef({
          owner,
          repo: repoName,
          ref: `refs/tags/${tagName}`,
          sha: commitSha,
        });
        tag = tagName;
      }
    } catch {
      // non-fatal: proceed without commitSha/tag
    }

    const repoUrl = `https://github.com/${owner}/${repoName}`;
    return { success: true, repoUrl, defaultBranch: branch, commitSha, tag };
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    const status = err && typeof err === "object" && "status" in err ? (err as { status: number }).status : undefined;
    if (msg.includes("Bad credentials") || status === 401) {
      return {
        success: false,
        error:
          "GitHub token invalid or expired. Set a valid GITHUB_TOKEN (or GITHUB_ACCESS_TOKEN) in supabase-mt/.env.local with repo scope (GitHub → Settings → Developer settings → Personal access tokens). Restart the dev server after changing.",
      };
    }
    return { success: false, error: msg };
  }
}

export type DeleteGitHubRepoResult =
  | { success: true }
  | { success: false; error: string };

/**
 * Parse GitHub repo URL to owner and repo name.
 * Supports https://github.com/owner/repo and https://github.com/owner/repo.git
 */
export function parseRepoUrl(repoUrl: string): { owner: string; repo: string } | null {
  const trimmed = repoUrl?.trim();
  if (!trimmed) return null;
  try {
    const url = new URL(trimmed);
    if (url.hostname !== "github.com" && !url.hostname.endsWith(".github.com")) return null;
    const pathParts = url.pathname.replace(/^\/+/, "").split("/").filter(Boolean);
    if (pathParts.length < 2) return null;
    const owner = pathParts[0];
    let repo = pathParts[1];
    if (repo.endsWith(".git")) repo = repo.slice(0, -4);
    if (!owner || !repo) return null;
    return { owner, repo };
  } catch {
    return null;
  }
}

/**
 * Delete a GitHub repository. Requires GITHUB_TOKEN with delete_repo scope (or repo scope).
 * repoUrl should be the full URL (e.g. https://github.com/owner/repo) stored on the project.
 */
export async function deleteGitHubRepo(repoUrl: string): Promise<DeleteGitHubRepoResult> {
  const token = getGitHubToken();
  if (!token) return { success: false, error: "GITHUB_TOKEN or GITHUB_ACCESS_TOKEN not set." };

  const parsed = parseRepoUrl(repoUrl);
  if (!parsed) return { success: false, error: `Invalid GitHub repo URL: ${repoUrl}` };

  const octokit = new Octokit({ auth: token });
  try {
    await octokit.rest.repos.delete({
      owner: parsed.owner,
      repo: parsed.repo,
    });
    return { success: true };
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    const status = err && typeof err === "object" && "status" in err ? (err as { status: number }).status : undefined;
    if (status === 404) return { success: true }; // already deleted
    if (msg.includes("Bad credentials") || status === 401) {
      return { success: false, error: "GitHub token invalid or expired." };
    }
    return { success: false, error: msg };
  }
}
