import type {
  Formula,
  FragranceOil,
  DashboardStats,
} from "./types"

// ---- Sample Fragrance Oils (inspired by MNKY Science DB) ----
export const FRAGRANCE_OILS: FragranceOil[] = [
  {
    id: "fo-001",
    name: "Forest Chai",
    description:
      "A warming blend of spiced chai tea set against a backdrop of deep evergreen forest. Cardamom and ginger weave through layers of fir and cinnamon.",
    topNotes: ["Orange Peel", "Peppercorn", "Cardamom"],
    middleNotes: ["Ginger", "Anise", "Nutmeg"],
    baseNotes: ["Fir", "Cinnamon", "Honey"],
    category: "Spicy",
    type: "Fragrance Oil",
    candleSafe: true,
    soapSafe: true,
    lotionSafe: true,
    perfumeSafe: false,
    roomSpraySafe: true,
    waxMeltSafe: true,
    maxUsageCandle: 10,
    maxUsageSoap: 6,
    maxUsageLotion: 3,
    price1oz: 4.25,
    price4oz: 13.5,
    price16oz: 42.0,
    rating: 4.8,
    reviewCount: 124,
    blendsWellWith: ["Vanilla Bean", "Smoked Oud", "Amber Noir"],
    alternativeBranding: ["Forested Escape"],
    suggestedColors: ["Deep Green", "Warm Brown", "Amber"],
  },
  {
    id: "fo-002",
    name: "Caribbean Casita",
    description:
      "Transport yourself to a sun-drenched island home with notes of fresh coconut, tropical flowers, and warm driftwood.",
    topNotes: ["Lime Zest", "Sea Salt", "Coconut Water"],
    middleNotes: ["Plumeria", "Jasmine", "Ylang Ylang"],
    baseNotes: ["Driftwood", "Vanilla", "Musk"],
    category: "Tropical",
    type: "Fragrance Oil",
    candleSafe: true,
    soapSafe: true,
    lotionSafe: true,
    perfumeSafe: true,
    roomSpraySafe: true,
    waxMeltSafe: true,
    maxUsageCandle: 12,
    maxUsageSoap: 6,
    maxUsageLotion: 4,
    price1oz: 4.5,
    price4oz: 14.0,
    price16oz: 44.0,
    rating: 4.9,
    reviewCount: 208,
    blendsWellWith: ["Mango Tango", "Ocean Breeze", "Warm Sand"],
    alternativeBranding: ["Island Retreat"],
    suggestedColors: ["Ocean Blue", "Sandy Beige", "Coral"],
  },
  {
    id: "fo-003",
    name: "Formal Affair",
    description:
      "A sophisticated and elegant fragrance evoking a black-tie gala. Rich oud and leather blend with champagne accord and white florals.",
    topNotes: ["Champagne Accord", "Bergamot", "Pink Pepper"],
    middleNotes: ["White Rose", "Peony", "Orris"],
    baseNotes: ["Oud", "Leather", "Amber"],
    category: "Luxurious",
    type: "Fragrance Oil",
    candleSafe: true,
    soapSafe: false,
    lotionSafe: true,
    perfumeSafe: true,
    roomSpraySafe: true,
    waxMeltSafe: true,
    maxUsageCandle: 10,
    maxUsageSoap: 0,
    maxUsageLotion: 3,
    price1oz: 5.25,
    price4oz: 16.5,
    price16oz: 52.0,
    rating: 4.7,
    reviewCount: 89,
    blendsWellWith: ["Smoked Oud", "Velvet Noir", "Black Tie"],
    alternativeBranding: ["Black Tie Gala"],
    suggestedColors: ["Black", "Gold", "Deep Burgundy"],
  },
  {
    id: "fo-004",
    name: "Lavender Dreams",
    description:
      "A calming journey through rolling lavender fields at twilight. French lavender meets soft chamomile and warm vanilla.",
    topNotes: ["Lavender", "Lemon Verbena"],
    middleNotes: ["Chamomile", "Clary Sage", "Violet Leaf"],
    baseNotes: ["Vanilla", "Sandalwood", "White Musk"],
    category: "Floral",
    type: "Fragrance Oil",
    candleSafe: true,
    soapSafe: true,
    lotionSafe: true,
    perfumeSafe: true,
    roomSpraySafe: true,
    waxMeltSafe: true,
    maxUsageCandle: 12,
    maxUsageSoap: 6,
    maxUsageLotion: 5,
    price1oz: 3.75,
    price4oz: 12.0,
    price16oz: 38.0,
    rating: 4.9,
    reviewCount: 312,
    blendsWellWith: ["Vanilla Bean", "Eucalyptus", "Chamomile"],
    alternativeBranding: ["Twilight Fields"],
    suggestedColors: ["Soft Purple", "Lavender", "Cream"],
  },
  {
    id: "fo-005",
    name: "Smoked Oud",
    description:
      "A rich, complex base note element. Deep smoky oud wood with hints of dark amber and incense. Perfect for layering and adding depth.",
    topNotes: ["Black Pepper"],
    middleNotes: ["Incense", "Dark Rose"],
    baseNotes: ["Oud Wood", "Smoke", "Dark Amber"],
    category: "Woody",
    type: "Blending Element",
    candleSafe: true,
    soapSafe: true,
    lotionSafe: false,
    perfumeSafe: true,
    roomSpraySafe: true,
    waxMeltSafe: true,
    maxUsageCandle: 8,
    maxUsageSoap: 4,
    maxUsageLotion: 0,
    price1oz: 6.0,
    price4oz: 18.5,
    price16oz: 58.0,
    rating: 4.6,
    reviewCount: 67,
    blendsWellWith: ["Forest Chai", "Formal Affair", "Amber Noir"],
    alternativeBranding: ["Dark Embers"],
    suggestedColors: ["Charcoal", "Deep Brown", "Black"],
  },
  {
    id: "fo-006",
    name: "Citrus Grove",
    description:
      "Bright and invigorating, this blend captures the essence of a Mediterranean citrus orchard at peak harvest. Zesty and uplifting.",
    topNotes: ["Blood Orange", "Grapefruit", "Lemon"],
    middleNotes: ["Neroli", "Green Tea"],
    baseNotes: ["White Cedar", "Light Musk"],
    category: "Fresh",
    type: "Fragrance Oil",
    candleSafe: true,
    soapSafe: true,
    lotionSafe: true,
    perfumeSafe: true,
    roomSpraySafe: true,
    waxMeltSafe: true,
    maxUsageCandle: 10,
    maxUsageSoap: 6,
    maxUsageLotion: 4,
    price1oz: 3.5,
    price4oz: 11.0,
    price16oz: 35.0,
    rating: 4.7,
    reviewCount: 185,
    blendsWellWith: ["Lavender Dreams", "Eucalyptus", "Mint"],
    alternativeBranding: ["Sun Harvest"],
    suggestedColors: ["Bright Orange", "Yellow", "Light Green"],
  },
]

// ---- Sample Formulas ----
export const FORMULAS: Formula[] = [
  {
    id: "f-001",
    name: "Classic Soy Candle",
    productType: "candle",
    description:
      "A standard soy wax candle formula with optimal fragrance throw. Works well with most container types.",
    phases: [
      {
        id: "p-001",
        name: "Wax Phase",
        ingredients: [
          {
            id: "i-001",
            name: "464 Soy Wax",
            function: "Base Wax",
            percentage: 85,
          },
          {
            id: "i-002",
            name: "Coconut Oil (76 degree)",
            function: "Hot Throw Enhancer",
            percentage: 5,
          },
        ],
      },
      {
        id: "p-002",
        name: "Fragrance Phase",
        ingredients: [
          {
            id: "i-003",
            name: "Fragrance Oil",
            function: "Scent",
            percentage: 10,
            isFragranceOil: true,
          },
        ],
      },
    ],
    totalWeight: 400,
    source: "mood-mnky",
    tags: ["soy", "container", "beginner-friendly"],
    createdAt: "2025-08-15",
  },
  {
    id: "f-002",
    name: "Luxury Coconut Soy Blend",
    productType: "candle",
    description:
      "A premium coconut-soy blend for superior scent throw and smooth finish. Ideal for tumblers and specialty vessels.",
    phases: [
      {
        id: "p-003",
        name: "Wax Phase",
        ingredients: [
          {
            id: "i-004",
            name: "Coco-Soy Blend Wax",
            function: "Base Wax",
            percentage: 78,
          },
          {
            id: "i-005",
            name: "Beeswax",
            function: "Hardener / Texture",
            percentage: 5,
          },
          {
            id: "i-006",
            name: "Vybar 260",
            function: "Fragrance Binder",
            percentage: 2,
          },
        ],
      },
      {
        id: "p-004",
        name: "Additive Phase",
        ingredients: [
          {
            id: "i-007",
            name: "UV Inhibitor",
            function: "Color Stabilizer",
            percentage: 0.5,
          },
        ],
      },
      {
        id: "p-005",
        name: "Fragrance Phase",
        ingredients: [
          {
            id: "i-008",
            name: "Fragrance Oil",
            function: "Scent",
            percentage: 12,
            isFragranceOil: true,
          },
          {
            id: "i-009",
            name: "Candle Dye Chips",
            function: "Color",
            percentage: 2.5,
          },
        ],
      },
    ],
    totalWeight: 450,
    source: "mood-mnky",
    tags: ["coconut", "luxury", "premium"],
    createdAt: "2025-09-01",
  },
  {
    id: "f-003",
    name: "Deep Conditioning Hair Mask",
    productType: "lotion",
    description:
      "A rich conditioning treatment inspired by Whole Elise formulations. Features a heated phase with butters and a cool-down phase with oils and actives.",
    phases: [
      {
        id: "p-006",
        name: "Heated Phase",
        ingredients: [
          {
            id: "i-010",
            name: "Shea Butter",
            function: "Emollient",
            percentage: 25,
          },
          {
            id: "i-011",
            name: "Coconut Oil",
            function: "Conditioning",
            percentage: 20,
          },
          {
            id: "i-012",
            name: "Mango Butter",
            function: "Emollient",
            percentage: 10,
          },
          {
            id: "i-013",
            name: "Cetyl Alcohol",
            function: "Thickener",
            percentage: 5,
          },
        ],
      },
      {
        id: "p-007",
        name: "Cool Down 1",
        ingredients: [
          {
            id: "i-014",
            name: "Olive Oil",
            function: "Conditioning",
            percentage: 15,
          },
          {
            id: "i-015",
            name: "Jojoba Oil",
            function: "Moisturizer",
            percentage: 10,
          },
          {
            id: "i-016",
            name: "Castor Oil",
            function: "Humectant",
            percentage: 10,
          },
        ],
      },
      {
        id: "p-008",
        name: "Cool Down 2",
        ingredients: [
          {
            id: "i-017",
            name: "Vitamin E",
            function: "Antioxidant",
            percentage: 2,
          },
          {
            id: "i-018",
            name: "Essential Oil Blend",
            function: "Fragrance / Therapeutic",
            percentage: 3,
            isFragranceOil: true,
          },
        ],
      },
    ],
    totalWeight: 500,
    source: "whole-elise",
    tags: ["hair", "conditioning", "butters"],
    createdAt: "2025-07-20",
  },
  {
    id: "f-004",
    name: "Moisturizing Body Lotion",
    productType: "lotion",
    description:
      "A lightweight yet deeply moisturizing body lotion. Perfect for daily use with your favorite MOOD MNKY fragrance.",
    phases: [
      {
        id: "p-009",
        name: "Oil Phase (Heated)",
        ingredients: [
          {
            id: "i-019",
            name: "Sweet Almond Oil",
            function: "Emollient",
            percentage: 12,
          },
          {
            id: "i-020",
            name: "Cetearyl Alcohol",
            function: "Emulsifier / Thickener",
            percentage: 5,
          },
          {
            id: "i-021",
            name: "Emulsifying Wax NF",
            function: "Emulsifier",
            percentage: 5,
          },
          {
            id: "i-022",
            name: "Shea Butter",
            function: "Emollient",
            percentage: 4,
          },
        ],
      },
      {
        id: "p-010",
        name: "Water Phase (Heated)",
        ingredients: [
          {
            id: "i-023",
            name: "Distilled Water",
            function: "Base",
            percentage: 60,
          },
          {
            id: "i-024",
            name: "Vegetable Glycerin",
            function: "Humectant",
            percentage: 5,
          },
        ],
      },
      {
        id: "p-011",
        name: "Cool Down",
        ingredients: [
          {
            id: "i-025",
            name: "Fragrance Oil",
            function: "Scent",
            percentage: 3,
            isFragranceOil: true,
          },
          {
            id: "i-026",
            name: "Preservative (Optiphen Plus)",
            function: "Preservative",
            percentage: 1.5,
          },
          {
            id: "i-027",
            name: "Vitamin E Oil",
            function: "Antioxidant",
            percentage: 0.5,
          },
          {
            id: "i-028",
            name: "Allantoin",
            function: "Skin Soother",
            percentage: 0.5,
          },
        ],
      },
    ],
    totalWeight: 300,
    source: "whole-elise",
    tags: ["body", "moisturizing", "daily"],
    createdAt: "2025-08-10",
  },
  {
    id: "f-005",
    name: "Cold Process Bar Soap",
    productType: "soap",
    description:
      "A classic cold-process soap formula with a balanced lather profile. Gentle enough for daily use on face and body.",
    phases: [
      {
        id: "p-012",
        name: "Oil Phase",
        ingredients: [
          {
            id: "i-029",
            name: "Olive Oil",
            function: "Conditioning",
            percentage: 35,
          },
          {
            id: "i-030",
            name: "Coconut Oil (76 degree)",
            function: "Cleansing / Lather",
            percentage: 25,
          },
          {
            id: "i-031",
            name: "Palm Oil (Sustainable)",
            function: "Hardness",
            percentage: 20,
          },
          {
            id: "i-032",
            name: "Shea Butter",
            function: "Luxury / Conditioning",
            percentage: 7,
          },
          {
            id: "i-033",
            name: "Castor Oil",
            function: "Lather Boost",
            percentage: 5,
          },
        ],
      },
      {
        id: "p-013",
        name: "Lye Phase",
        ingredients: [
          {
            id: "i-034",
            name: "Sodium Hydroxide (NaOH)",
            function: "Saponifier",
            percentage: 5,
          },
        ],
      },
      {
        id: "p-014",
        name: "Additives",
        ingredients: [
          {
            id: "i-035",
            name: "Fragrance Oil",
            function: "Scent",
            percentage: 3,
            isFragranceOil: true,
          },
        ],
      },
    ],
    totalWeight: 1000,
    source: "mood-mnky",
    tags: ["cold-process", "bar", "gentle"],
    createdAt: "2025-10-01",
  },
  {
    id: "f-006",
    name: "Room Spray Mist",
    productType: "room-spray",
    description:
      "A simple yet effective room spray formula. Quick to make with impressive scent diffusion.",
    phases: [
      {
        id: "p-015",
        name: "Base Phase",
        ingredients: [
          {
            id: "i-036",
            name: "Distilled Water",
            function: "Base",
            percentage: 72,
          },
          {
            id: "i-037",
            name: "Isopropyl Alcohol (91%)",
            function: "Solvent / Dispersant",
            percentage: 15,
          },
        ],
      },
      {
        id: "p-016",
        name: "Fragrance Phase",
        ingredients: [
          {
            id: "i-038",
            name: "Polysorbate 20",
            function: "Emulsifier",
            percentage: 5,
          },
          {
            id: "i-039",
            name: "Fragrance Oil",
            function: "Scent",
            percentage: 8,
            isFragranceOil: true,
          },
        ],
      },
    ],
    totalWeight: 240,
    source: "mood-mnky",
    tags: ["spray", "easy", "quick"],
    createdAt: "2025-11-05",
  },
  {
    id: "f-007",
    name: "Wax Melt Tart",
    productType: "wax-melt",
    description:
      "A high-fragrance wax melt formula designed for maximum scent throw in warmers. Uses a parasoy blend for consistent performance.",
    phases: [
      {
        id: "p-017",
        name: "Wax Phase",
        ingredients: [
          {
            id: "i-040",
            name: "Parasoy Blend Wax",
            function: "Base Wax",
            percentage: 85,
          },
        ],
      },
      {
        id: "p-018",
        name: "Fragrance Phase",
        ingredients: [
          {
            id: "i-041",
            name: "Fragrance Oil",
            function: "Scent",
            percentage: 15,
            isFragranceOil: true,
          },
        ],
      },
    ],
    totalWeight: 80,
    source: "mood-mnky",
    tags: ["wax-melt", "high-fragrance", "warmer"],
    createdAt: "2025-11-12",
  },
]

// ---- Dashboard Stats ----
export const DASHBOARD_STATS: DashboardStats = {
  totalFormulas: FORMULAS.length,
  totalFragrances: FRAGRANCE_OILS.length,
  totalProducts: 24,
  recentActivity: [
    {
      id: "a-001",
      action: "Created formula",
      target: "Wax Melt Tart",
      timestamp: "2 hours ago",
    },
    {
      id: "a-002",
      action: "Updated fragrance",
      target: "Forest Chai",
      timestamp: "5 hours ago",
    },
    {
      id: "a-003",
      action: "Pushed to Shopify",
      target: "Caribbean Casita 16oz Tin",
      timestamp: "1 day ago",
    },
    {
      id: "a-004",
      action: "Created formula",
      target: "Room Spray Mist",
      timestamp: "2 days ago",
    },
    {
      id: "a-005",
      action: "Synced from Notion",
      target: "6 fragrance oils updated",
      timestamp: "3 days ago",
    },
  ],
}
