#!/usr/bin/env bash
# =============================================================================
# start-local.sh — Pull Supabase status values into .env for local dev
# =============================================================================
# Run from docker-compose/ or repo root. Requires: supabase start --workdir supabase-mt
# Usage: ./scripts/start-local.sh [--output .env|.env.local]
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$COMPOSE_DIR/../.." && pwd)"
OUTPUT_FILE=".env"

while [[ $# -gt 0 ]]; do
  case $1 in
    --output)
      OUTPUT_FILE="$2"
      shift 2
      ;;
    *)
      shift
      ;;
  esac
done

cd "$REPO_ROOT"

if ! command -v supabase &>/dev/null; then
  echo "Error: supabase CLI not found. Install: npm i -g supabase" >&2
  exit 1
fi

# Prefer supabase status -o env (outputs env vars directly)
STATUS_ENV=$(supabase status --workdir supabase-mt --output env 2>/dev/null || true)
if [[ -n "$STATUS_ENV" ]]; then
  API_URL=$(echo "$STATUS_ENV" | grep -E '^API_URL=' | cut -d= -f2- | tr -d '"' | xargs || true)
  ANON_KEY=$(echo "$STATUS_ENV" | grep -E '^ANON_KEY=' | cut -d= -f2- | tr -d '"' | xargs || true)
  SERVICE_ROLE_KEY=$(echo "$STATUS_ENV" | grep -E '^SERVICE_ROLE_KEY=' | cut -d= -f2- | tr -d '"' | xargs || true)
  STUDIO_URL=$(echo "$STATUS_ENV" | grep -E '^STUDIO_URL=' | cut -d= -f2- | tr -d '"' | xargs || true)
  DB_URL=$(echo "$STATUS_ENV" | grep -E '^DB_URL=' | cut -d= -f2- | tr -d '"' | xargs || true)
  INBOUND_URL=$(echo "$STATUS_ENV" | grep -E '^INBOUND_URL=' | cut -d= -f2- | tr -d '"' | xargs || true)
  # Fallback: grep from plain supabase status if env vars use different names
  if [[ -z "$API_URL" ]]; then
    STATUS_PLAIN=$(supabase status --workdir supabase-mt 2>/dev/null || true)
    API_URL=$(echo "$STATUS_PLAIN" | grep -E 'API URL:' | sed 's/.*URL:\s*//' | xargs || true)
    ANON_KEY=$(echo "$STATUS_PLAIN" | grep -iE 'anon key:' | sed 's/.*key:\s*//' | xargs || true)
    SERVICE_ROLE_KEY=$(echo "$STATUS_PLAIN" | grep -iE 'service_role key:' | sed 's/.*key:\s*//' | xargs || true)
    STUDIO_URL=$(echo "$STATUS_PLAIN" | grep -E 'Studio URL:' | sed 's/.*URL:\s*//' | xargs || true)
    DB_URL=$(echo "$STATUS_PLAIN" | grep -E 'DB URL:' | sed 's/.*URL:\s*//' | xargs || true)
    INBOUND_URL=$(echo "$STATUS_PLAIN" | grep -E 'Inbucket URL:' | sed 's/.*URL:\s*//' | xargs || true)
  fi
fi

if [[ -z "$API_URL" ]]; then
  echo "Error: supabase status failed. Ensure Supabase is running: supabase start --workdir supabase-mt" >&2
  exit 1
fi

# Supabase local storage S3 keys (from .env.local.example)
STORAGE_ACCESS_KEY="625729a08b95bf1b7ff351a663f3a23c"
STORAGE_SECRET_KEY="850181e4652dd023b7a98c58ae0d2d34bd487ee0cc3254aed6eda37307425907"

ENV_PATH="$COMPOSE_DIR/$OUTPUT_FILE"
mkdir -p "$(dirname "$ENV_PATH")"

# Merge or create
if [[ -f "$ENV_PATH" ]]; then
  TMP=$(mktemp 2>/dev/null || echo "$ENV_PATH.tmp")
  while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ "$line" =~ ^NEXT_PUBLIC_SUPABASE_MT_URL= ]]; then
      echo "NEXT_PUBLIC_SUPABASE_MT_URL=$API_URL"
    elif [[ "$line" =~ ^NEXT_PUBLIC_SUPABASE_MT_ANON_KEY= ]]; then
      echo "NEXT_PUBLIC_SUPABASE_MT_ANON_KEY=$ANON_KEY"
    elif [[ "$line" =~ ^SUPABASE_MT_SERVICE_ROLE_KEY= ]]; then
      echo "SUPABASE_MT_SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY"
    elif [[ "$line" =~ ^SUPABASE_STUDIO_URL= ]]; then
      echo "SUPABASE_STUDIO_URL=$STUDIO_URL"
    elif [[ "$line" =~ ^SUPABASE_MAILPIT_URL= ]]; then
      echo "SUPABASE_MAILPIT_URL=$INBOUND_URL"
    elif [[ "$line" =~ ^SUPABASE_DATABASE_URL= ]]; then
      [[ -n "$DB_URL" ]] && echo "SUPABASE_DATABASE_URL=$DB_URL"
    else
      echo "$line"
    fi
  done < "$ENV_PATH" > "$TMP"
  mv "$TMP" "$ENV_PATH"
else
  {
    echo "# Auto-generated by scripts/start-local.sh"
    echo "SUPABASE_MODE=local"
    echo "NEXT_PUBLIC_SUPABASE_MT_URL=$API_URL"
    echo "NEXT_PUBLIC_SUPABASE_MT_ANON_KEY=$ANON_KEY"
    echo "SUPABASE_MT_SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY"
    echo "SUPABASE_STUDIO_URL=$STUDIO_URL"
    echo "SUPABASE_MAILPIT_URL=$INBOUND_URL"
    [[ -n "$DB_URL" ]] && echo "SUPABASE_DATABASE_URL=$DB_URL"
    echo "SUPABASE_STORAGE_URL=$API_URL/storage/v1/s3"
    echo "SUPABASE_STORAGE_ACCESS_KEY=$STORAGE_ACCESS_KEY"
    echo "SUPABASE_STORAGE_SECRET_KEY=$STORAGE_SECRET_KEY"
    echo "SUPABASE_STORAGE_REGION=local"
  } > "$ENV_PATH"
fi

echo "Updated $OUTPUT_FILE with Supabase local values."
echo "API URL: $API_URL"
echo "Studio:  $STUDIO_URL"
